# Site settings
title: Nathaniel Arellano
email: nathaniel.arellano@gmail.com
description: >
  A blog for Nathaniel to write about technology, hikes, cars, and experiences.
baseurl: ""
url: "http://nathanielarellano.com"
fixedNav: 'true' # true or false
theme: blue # green, blue, orange, purple, grey
twitterUsername: tanyxp
githubUsername: tanyxp
instagramUsername: tanyxp

# Build settings
permalink: /:year/:month/:title
markdown: kramdown
include: [_pages, _images]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed
